import "./globals.css";

import Link from "next/link";
import type { Metadata } from "next";
import { Providers } from "@/context/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/favicon.svg" />
      </head>

        <Providers>
        <body>
           <nav className="sticky h-16 top-0 px-6 py-4 flex items-center bg-white z-50 shadow">
            <Link href="/">
              <h1 className="text-2xl font-bold">
                SAT Bluebook
              </h1>
            </Link>
          </nav>
          {children}
          </body>
      </Providers>
    </html>
  );
}
