"use client";

import "./globals.css";

import { AppShell, Header, MantineProvider, Text } from "@mantine/core";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/favicon.svg" />
      </head>

      <body>
        <MantineProvider withNormalizeCSS withGlobalStyles>
          <nav className="sticky h-16 top-0 px-6 py-4 flex items-center bg-white z-50 shadow">
            <h1 className="text-2xl font-bold">
              SAT{" "}
              <Text component="span" inherit variant="gradient">
                Bluebook
              </Text>
            </h1>
          </nav>

          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
